### ISSUE TITLE
Cleverbot API

### ISSUE THREAD

**Issue by ToniTurnerr** [ToniTurnerr/jackbot#1]
Cleverbot API crashes the bot for some unknown reason. Was fine until yesterday however it broke today.

undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\Administrator\Desktop\jackbot\node_modules\cleverbot.io\app.js:37:14)
    at Request.self.callback (C:\Users\Administrator\Desktop\jackbot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Administrator\Desktop\jackbot\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Desktop\jackbot\node_modules\request\request.js:1085:12)

**Comment by ToniTurnerr** [comment]
Seems to be fixed but it's really slow. No errors on the console, could be the API.

**Comment by ToniTurnerr** [comment]
Nevermind, still crashes.

**Comment by ToniTurnerr** [comment]
Removed, closing the issue.
